//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Windows.Forms;

public class FileHelper
{
    // ---------------------- Fields ----------------------

    //private string fileName;

    // ------------------- Constructors -------------------

    public FileHelper()
    {
        FileName = null;
    }

    // ------------------- Properties ---------------------

    public string FileName { get; set; }

    // --------------------- Methods ----------------------

    public void saveToFile(Network myNetwork)
	{
        try
        {
            FileStream fs = new FileStream(FileName, FileMode.OpenOrCreate, FileAccess.Write);
            BinaryFormatter bf = new BinaryFormatter();

            bf.Serialize(fs, myNetwork);

            if (fs != null)
                fs.Close();
        }
        catch (IOException)
        {
            MessageBox.Show("Error closing file");
        }
    }

	public Network loadFromFile()
	{
        Network loadedNetwork = null;

        FileStream fs = new FileStream(FileName, FileMode.Open, FileAccess.Read);
        BinaryFormatter bf = new BinaryFormatter();

        loadedNetwork = (Network)bf.Deserialize(fs);

        if (fs != null)
            fs.Close();

        return loadedNetwork;
    }
}

