//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

[Serializable]
public class Merger : Component
{
    // ---------------------- Fields ----------------------
    private int outflow;

    // ------------------- Constructors -------------------
    public Merger(Point location) : base(location)
    {
        outflow = 0;
    }

    // ------------------- Properties -------------------
    public int Outflow { get { return outflow; } set { outflow = value; } }

    // --------------------- Methods ----------------------
    public override void recalculateFlow(int newFlow)
    {
        int flow = 0;
        for(int i = 0; i < 2; i++)
        {
            if (PipelineList[i] != null)
            {
                flow += PipelineList[i].CurrentFlow;
            }
        }
        if (PipelineList[2]!=null)
        {
            PipelineList[2].recalculateFlow(flow);
        }
    }
}

