//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

[Serializable]
public class PumpSink : Component
{
    // ---------------------- Fields ----------------------
    private int maxFlow;

    private int currentFlow;

    private bool isSink;

    // ------------------- Constructors -------------------
    public PumpSink(int currentFlow, int maxFlow, bool isSink, Point location) : base(location)
    {
        this.isSink = isSink;
        this.currentFlow = currentFlow;
        this.maxFlow = maxFlow;
    }

    // ------------------- Properties -------------------
    public int MaxFlow { get { return maxFlow; } set { maxFlow = value; } }
    public int CurrentFlow { get { return currentFlow; } set { currentFlow = value; } }
    public bool IsSink { get { return isSink; } set { isSink = value; } }

    // --------------------- Methods ----------------------
    public bool changeCurrentFlow(int newFlow)
	{
		if(newFlow <= maxFlow)
        {
            recalculateFlow(newFlow);
            return true;
        }
        else
        {
            return false;
        }
	}

	public void changeMaxFlow(int newMaxFlow)
	{
        maxFlow = newMaxFlow;
	}

    public override void recalculateFlow(int newFlow)
    {
        currentFlow = newFlow;
        if (!isSink)
        {
            if(PipelineList.Count > 0)
            {
                if (PipelineList[0] != null)
                    PipelineList[0].recalculateFlow(newFlow);
            }
        }
    }
   

}

