//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AdjustableSplitter : Splitter
{
	private int topPercentage
	{
		get;
		set;
	}

	public void changeSplitterPercentage(int newPercentage)
	{
		throw new System.NotImplementedException();
	}

	public AdjustableSplitter(int topPercentage)
	{
	}

}

