//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
	private Point position
	{
		get;
		set;
	}

	private IEnumerable<Pipeline> pipelineArray
	{
		get;
		set;
	}

	public IEnumerable<Pipeline> Pipeline
	{
		get;
		set;
	}

	private void changeStateInOut(Point location, bool state)
	{
		throw new System.NotImplementedException();
	}

	public Component(Point location)
	{
        this.position = location;
	}

	public void recalculateFlow(int newFlow)
	{
		throw new System.NotImplementedException();
	}

	public void draw()
	{
		throw new System.NotImplementedException();
	}

}

