//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FileHelper
{
	private string fileName
	{
		get;
		set;
	}

	public void saveToFile(string fileName,Network myNetwork)
	{
		throw new System.NotImplementedException();
	}

	public Network loadFromFile(string fileName)
	{
		throw new System.NotImplementedException();
	}

}

