//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Form1
{
	private Network myNetwork
	{
		get;
		set;
	}

	public Network Network
	{
		get;
		set;
	}

	public IEnumerable<Toolbox> Toolbox
	{
		get;
		set;
	}

	public FileHelper FileHelper
	{
		get;
		set;
	}

}

