//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pipeline
{
	private IEnumerable<Components> connection
	{
		get;
		set;
	}

	private int safetyLimit
	{
		get;
		set;
	}

	private int currentFlow
	{
		get;
		set;
	}

	private List<Point> inbetweenPoints
	{
		get;
		set;
	}

	public Pipeline(Component  outComp, Component  inComp, List<Point> inbetweenPoints, int safetyLimit)
	{
	}

	public void recalculateFlow(int NewFlow)
	{
		throw new System.NotImplementedException();
	}

	public void draw()
	{
		throw new System.NotImplementedException();
	}

}

