//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Splitter : Component
{
	private bool inState
	{
		get;
		set;
	}

	private IEnumerable<bool> outState
	{
		get;
		set;
	}

	private int inflow
	{
		get;
		set;
	}

	private int outflowUp
	{
		get;
		set;
	}

	private int outflowBottom
	{
		get;
		set;
	}

}

