//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Toolbox
{
	private toolsCollection currentTool
	{
		get;
		set;
	}

	public void changeCurrentTool(toolsCollection theTool)
	{
		throw new System.NotImplementedException();
	}

}

